console.log(typeof 42); // Output: "number"
console.log(typeof 'Veinticinco'); // Output: "string"
console.log(typeof -666); // Output: "number"
console.log(typeof true); // Output: "boolean"
console.log(typeof 0); // Output: "number"
console.log(typeof ''); // Output: "string"
console.log(typeof null); // Output: "object"
console.log(typeof undefined); // Output: "undefined"
console.log(typeof false); // Output: "boolean"
console.log(typeof NaN); // Output: "number"
console.log(typeof 3.14); // Output: "number"
console.log(typeof 'Hello, World!'); // Output: "string"
console.log(typeof {}); // Output: "object"
console.log(typeof []); // Output: "object"
console.log(typeof function() {}); // Output: "function"
console.log(typeof Symbol('sym')); // Output: "symbol"  
console.log(typeof BigInt(12345678901234567890)); // Output: "bigint"
